# Build configuration for example app
#
# Explicitly enables the surreal_table_builder from the parent package

targets:
  $default:
    sources:
      - scenarios/**
      - $package$
    builders:
      surrealdartb|surreal_table_builder:
        enabled: true
        generate_for:
          - scenarios/**/*.dart
